# Generated by Django 3.1.3 on 2020-12-01 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('playlist_title', models.CharField(blank=True, max_length=200, null=True)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('songs', models.CharField(blank=True, max_length=300, null=True)),
                ('like_cnt', models.IntegerField(blank=True, null=True)),
                ('updt_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'playlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SongMeta',
            fields=[
                ('song_id', models.IntegerField(primary_key=True, serialize=False)),
                ('album_id', models.IntegerField(blank=True, null=True)),
                ('album_name', models.CharField(blank=True, max_length=200, null=True)),
                ('artist_id_basket', models.CharField(blank=True, max_length=200, null=True)),
                ('artist_name_basket', models.CharField(blank=True, max_length=200, null=True)),
                ('song_name', models.CharField(blank=True, max_length=200, null=True)),
                ('song_gn_gnr_basket', models.CharField(blank=True, max_length=200, null=True)),
                ('song_gn_dtl_gnr_basket', models.CharField(blank=True, max_length=200, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('url_link', models.CharField(blank=True, max_length=300, null=True)),
                ('album_image', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'song_meta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('age_group', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReactionTable',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='musicApp.userinfo')),
                ('reaction_state', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reaction_table',
                'managed': False,
            },
        ),
    ]
